In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix 
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression 
from sklearn.decomposition import PCA

In [2]:
df = pd.read_csv("sample_submission.csv")
df.keys()

Index(['ImageId', 'Label'], dtype='object')

In [32]:
X = pd.read_csv("train.csv")
X.tail()
#X.shape

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
41995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41996,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41997,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41999,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [33]:
Y = pd.read_csv("test.csv")
Y.head()
#Y.shape

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [43]:
res = pd.concat([X, Y], axis=1)
res.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [44]:
res.fillna(0,inplace=True)

In [45]:
x = res
y = res.loc[:,'label']

In [46]:
y

0        1
1        0
2        1
3        4
4        0
        ..
41995    0
41996    1
41997    7
41998    6
41999    9
Name: label, Length: 42000, dtype: int64

In [37]:
x_train = X
y1_train = X.loc[:,'label']
x_test = Y
y1_test = Y

In [38]:
x_train.fillna(0,inplace=True)
y1_train.fillna(0,inplace=True)
x_test.fillna(0,inplace=True)
y1_test.fillna(0,inplace=True)

In [10]:
x.shape

(42000, 1569)

In [11]:
sc = StandardScaler()
x_scale = sc.fit_transform(x)
x_scale

array([[-1.1970246 ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-1.54332147,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-1.1970246 ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.88075661,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.53445975,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.57335035,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [12]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=30)

In [13]:
m = LogisticRegression(max_iter=1000)
m.fit(X_train,y_train)
m.score(X_test,y_test)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.8478571428571429

In [14]:
pca = PCA(0.95)
x_pca  =pca.fit_transform(x)
x_pca.shape

(42000, 283)

In [15]:
pca.n_components_

283

In [16]:
X_train_pca,X_test_pca,y_train,y_test = train_test_split(x_pca,y,test_size=0.20,random_state=30)

In [17]:
m1 = LogisticRegression(max_iter=1500)
m1.fit(X_train_pca,y_train)
m1.score(X_test_pca,y_test)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.9116666666666666